### PR TITLE
File exclude for issue #1

### PR DESCRIPTION
**Pull request by gashcrumb**
Okay, finally got a chance to get this in place.  Added some simple command line parsing as well.  So you can specify -e and a comma separated list of regexs of file paths that shouldn't trigger a reload.

### CODE REVIEW

**Comment by davidB** [comment]
Can you keep/restore the indentation of 2 spaces.

**Comment by davidB** [comment]
And prefix private field with '_'.

**Comment by gashcrumb** [comment]
Sure, give me a few...  My IDE kinda went reformat-happy :-)

**Comment by davidB** [comment]
Thanks.

**Pull request merged**
